"""switch to start_at and end_at timestamps

Revision ID: af950b996471
Revises: 0004
Create Date: 2026-09-09 04:56:40.225238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('start_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('end_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('tasks', 'date_due')
    op.drop_column('tasks', 'time_start')
    op.drop_column('tasks', 'time_due')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('time_due', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('time_start', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('date_due', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'end_at')
    op.drop_column('tasks', 'start_at')
    # ### end Alembic commands ###
